version: 2

builds:
  - binary: registry-push
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
